### ISSUE TITLE
Truncate Operator failing for Bigquery

### ISSUE THREAD

**Issue by utkarsharma2** [astro-projects/astro#313]
Found below error when running Truncate Op. for Bigquery table.

```
FAILED    [ 25%][2022-04-13 03:22:07,787] {base_executor.py:82} INFO - Adding to queue: ['<TaskInstance: qzf6u3usex1b9ig6.test_stats_check_1_1649800307_truncate backfill__2016-01-01T00:00:00+00:00 [queued]>']
[2022-04-13 03:22:12,805] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=qzf6u3usex1b9ig6
AIRFLOW_CTX_TASK_ID=test_stats_check_1_1649800307_truncate
AIRFLOW_CTX_EXECUTION_DATE=2016-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2016-01-01T00:00:00+00:00
[2022-04-13 03:22:12,811] {credentials_provider.py:312} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2022-04-13 03:22:16,637] {credentials_provider.py:312} INFO - Getting connection using `google.auth.default()` since no key file is defined for hook.
[2022-04-13 03:22:21,021] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/utkarsharma/sandbox/astronomer/astro/.nox/dev/lib/python3.8/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 203, in _execute
    self._query_job.result()
  File "/Users/utkarsharma/sandbox/astronomer/astro/.nox/dev/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1498, in result
    do_get_result()
  File "/Users/utkarsharma/sandbox/astronomer/astro/.nox/dev/lib/python3.8/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/Users/utkarsharma/sandbox/astronomer/astro/.nox/dev/lib/python3.8/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/Users/utkarsharma/sandbox/astronomer/astro/.nox/dev/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1488, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/Users/utkarsharma/sandbox/astronomer/astro/.nox/dev/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/Users/utkarsharma/sandbox/astronomer/astro/.nox/dev/lib/python3.8/site-packages/google/api_core/future/polling.py", line 135, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 DELETE must have a WHERE clause at [1:1]
```

**Comment by kaxil** [comment]
closed by https://github.com/astro-projects/astro/pull/363
