### ISSUE TITLE
Unable to load_file when using nested NDJSON

### ISSUE THREAD

**Issue by tatiana** [astro-projects/astro#73]
Version: Astro 0.3.3

Astro is currently unable to load_file if the origin NDJSON is nested.

How to reproduce:
```
    github_nested_table = aql.load_file(
        path="gs://dag-authoring/github/github_nested_000000000007.ndjson",
        task_id="load_ndjson",
        #file_conn_id="google_cloud_default",
        output_table=Table(
            table_name="github_projects_counts_by_language",
            database="postgres",
            conn_id="postgres_conn"
        )
```

Output:
```
Traceback (most recent call last):
  File "/home/tati/.virtualenvs/astro-private/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/home/tati/.virtualenvs/astro-private/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'dict'

The above exception was the direct cause of the following exception:
```

**Comment by tatiana** [comment]
Some options are detailed in:
https://www.psycopg.org/docs/extras.html#json-adaptation

**Comment by dimberman** [comment]
We believe that a good first solution would be to flatten the ndjson and prefix the path to each key

**Comment by utkarsharma2** [comment]
PR - https://github.com/astro-projects/astro/pull/257 Closes part of the ticket. We are handling only single-level nesting. 
Ndjson - 
{"a": {"b": ["a", "b"]}}


But not, 

Ndjson - 
{"a": {"b": [{"a":  "a"}, {"c": "a"}]}}

Above Json results in - 
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'
[SQL: INSERT INTO tmp_astro.e23vd9fl2gkcn4zb_load_file__1 ("a.b") VALUES (%(a.b_m0)s)]
[parameters: {'a.b_m0': [{'a': 'a'}, {'c': 'a'}]}]

**Comment by kaxil** [comment]
@utkarsharma2 Are you planning to tackle the second case in a different PR?

**Comment by utkarsharma2** [comment]
@kaxil yes since we need an interface that is completely agnostic of the underline lib used to flatten Ndjson. My earlier assumption was to just expose the pandas json_normalize method to do this.
